# Generated by Django 2.0.3 on 2019-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_auto_20190722_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesproduct',
            options={'verbose_name': 'Sales Product', 'verbose_name_plural': 'Sales Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
    ]
