# Generated by Django 2.0.3 on 2019-07-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0004_auto_20190725_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesproduct',
            old_name='discription',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='salesproduct',
            name='unit_price',
        ),
    ]
