# Generated by Django 2.0.3 on 2019-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0005_auto_20190726_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproduct',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
