# Generated by Django 2.0.3 on 2019-07-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0008_auto_20190730_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
