# Generated by Django 2.0.3 on 2019-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0009_remove_product_selling_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company Information'},
        ),
        migrations.AddField(
            model_name='content',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='content',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='com_name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
    ]
