# Generated by Django 2.0.3 on 2019-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0010_auto_20190730_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='com_logo',
            field=models.ImageField(blank=True, upload_to='logo', verbose_name='Company Logo'),
        ),
    ]
