# Generated by Django 2.0.3 on 2019-07-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0011_content_com_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='total_buy',
            field=models.FloatField(default=0),
        ),
    ]
